---
- name: Configuration serveur multifonction LPIC-2
  hosts: servers
  become: true
  vars_files:
    - vars.yaml
    
  tasks:
    # === PRÉPARATION ===
    - name: Mise à jour du système
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Installation des paquets nécessaires
      apt:
        name:
          - isc-dhcp-server
          - samba
          - samba-common-bin
          - iptables-persistent
          - nginx
          - rsync
          - cron
        state: present

    # === DHCP ===
    - name: Configuration du fichier par défaut DHCP
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^#?INTERFACESv4='
        line: 'INTERFACESv4="{{ dhcp_interface }}"'
        create: yes

    - name: Configuration DHCP principale
      template:
        src: templates/dhcp.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        backup: yes

    - name: Activation du service DHCP
      systemd:
        name: isc-dhcp-server
        enabled: yes
        state: started

    # === SAMBA ===
    - name: Création du groupe compta
      group:
        name: compta
        state: present

    - name: Création des répertoires de partage
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{ public_dir }}"
        - "{{ compta_dir }}"

    - name: Configuration Samba
      template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        backup: yes
      notify: restart samba

    - name: Création des utilisateurs système et Samba
      shell: |
        # Créer utilisateur système s'il n'existe pas
        if ! id {{ item.name }} &>/dev/null; then
          useradd -M -s /usr/sbin/nologin {{ item.name }}
        fi
        {% if item.groups and item.groups != '' %}
        # Ajouter au groupe si spécifié
        usermod -a -G {{ item.groups }} {{ item.name }}
        {% endif %}
        # Gérer utilisateur Samba (supprimer puis recréer pour éviter les conflits)
        smbpasswd -x {{ item.name }} 2>/dev/null || true
        (echo "{{ item.password }}"; echo "{{ item.password }}") | smbpasswd -a -s {{ item.name }}
      loop: "{{ samba_users }}"

    # === FIREWALL ===
    - name: Création du script firewall
      template:
        src: templates/firewall.sh.j2
        dest: /opt/firewall.sh
        mode: '0755'

    - name: Application du firewall
      shell: /opt/firewall.sh

    # === NGINX INTRANET ===
    - name: Création du répertoire web intranet
      file:
        path: /var/www/intranet
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Configuration nginx intranet
      template:
        src: templates/nginx-intranet.conf.j2
        dest: /etc/nginx/sites-available/intranet

    - name: Activation du site intranet
      file:
        src: /etc/nginx/sites-available/intranet
        dest: /etc/nginx/sites-enabled/intranet
        state: link
        force: yes

    - name: Désactivation du site par défaut nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Création de la page d'accueil intranet
      template:
        src: templates/intranet-index.html.j2
        dest: /var/www/intranet/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    # === SAUVEGARDE AUTOMATIQUE ===
    - name: Création du répertoire de sauvegarde
      file:
        path: /backup
        state: directory
        mode: '0750'

    - name: Création du script de sauvegarde
      template:
        src: templates/backup.sh.j2
        dest: /opt/backup.sh
        mode: '0755'

    - name: Configuration cron pour sauvegarde quotidienne
      cron:
        name: "Sauvegarde quotidienne Samba"
        minute: "0"
        hour: "2"
        job: "/opt/backup.sh"
        user: root

    # === DÉMARRAGE DES SERVICES ===
    - name: Démarrage des services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - isc-dhcp-server
        - smbd
        - nmbd
        - nginx
      ignore_errors: true

    - name: Redémarrage de nginx pour appliquer la configuration intranet
      systemd:
        name: nginx
        state: restarted

  handlers:
    - name: restart samba
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - smbd
        - nmbd