---
- name: Configuration serveur multifonction LPIC-2
  hosts: servers
  become: true
  vars_files:
    - vars.yml
    
  tasks:
    # === PRÉPARATION ===
    - name: Mise à jour du système
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Installation des paquets nécessaires
      apt:
        name:
          - isc-dhcp-server
          - samba
          - samba-common-bin
          - iptables-persistent
        state: present

    # === DHCP ===
    - name: Configuration DHCP
      template:
        src: templates/dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        backup: yes
      notify: restart dhcp

    - name: Activation du service DHCP
      systemd:
        name: isc-dhcp-server
        enabled: yes
        state: started

    # === SAMBA ===
    - name: Création du groupe compta
      group:
        name: compta
        state: present

    - name: Création des répertoires de partage
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{ public_dir }}"
        - "{{ compta_dir }}"

    - name: Configuration Samba
      template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        backup: yes
      notify: restart samba

    - name: Création des utilisateurs Samba
      shell: |
        useradd -M -s /usr/sbin/nologin {{ item.name }} || true
        {% if item.groups %}usermod -a -G {{ item.groups }} {{ item.name }}{% endif %}
        echo -e "{{ item.password }}\n{{ item.password }}" | smbpasswd -a -s {{ item.name }}
      loop: "{{ samba_users }}"
      no_log: true

    # === FIREWALL ===
    - name: Création du script firewall
      template:
        src: templates/firewall.sh.j2
        dest: /opt/firewall.sh
        mode: '0755'

    - name: Application du firewall
      shell: /opt/firewall.sh

    # === VÉRIFICATIONS ===
    - name: Vérification des services
      systemd:
        name: "{{ item }}"
        state: started
      loop:
        - isc-dhcp-server
        - smbd
        - nmbd

  handlers:
    - name: restart dhcp
      systemd:
        name: isc-dhcp-server
        state: restarted

    - name: restart samba
      systemd:
        name: smbd
        state: restarted
      listen: restart samba
      
    - name: restart nmbd
      systemd:
        name: nmbd
        state: restarted
      listen: restart samba